---
- hosts: all
  vars:
    # JAVA ROLE
    java_oracle_distribution: jdk
    java_oracle_version: 8u66
    # TOMCAT ROLE
    tomcat_version: 8.0.29
    util_init_system: systemd
    tomcat_instances:
      - name: geoserver
        service_name: geoserver
        service_file: geoserver.service
        path: /srv/geoserver
        user: tomcat
        port_ajp: 8009
        port_connector: 8080
        port_redirect: 8443
        catalina_opts: "-DGEOSERVER_DATA_DIR=/srv/geoserver/data/ -Xmx2048m -Xms2048m -XX:MetaspaceSize=512m -DGEOSERVER_NODE_OPTS=id:$host_ip -DGEOSERVER_AUDIT_PATH={{ geoserver_audit_dir }} -DGEOSERVER_LOG_LOCATION={{ geoserver_logs_dir }}geoserver.log"
    #GEOSERVER ROLE
    #must be equal to the path in the tomcat_instances
    geoserver_catalina_base: /srv/geoserver
    #location of the geoserver zip distribution
    war1_url: http://ares.boundlessgeo.com/geoserver/2.10.x/geoserver-2.10.x-latest-war.zip
  roles:
    - { role: silpion.java }
    - { role: silpion.tomcat }
    - { role: fds.geoserver }
