- name: silpion.util
  src: https://github.com/silpion/ansible-util

- name: silpion.java
  src: https://github.com/silpion/ansible-java

- name: silpion.tomcat
  src: https://github.com/silpion/ansible-tomcat
